    name: Pytest Workflow

    on:
      push:
        branches:
          - main

    jobs:
      test:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12' # Specify your desired Python version
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest
            # Install any other project dependencies
        - name: Run Pytest
          run: pytest